from os import environ

JWT_ACCESS_SECRET = environ["JWT_ACCESS_SECRET"]
JWT_REFRESH_SECRET = environ["JWT_REFRESH_SECRET"]
JWT_ALGORITHM = environ["JWT_ALGORITHM"]
JWT_ACCESS_MINUTES = environ["JWT_ACCESS_MINUTES"]
JWT_REFRESH_DAYS = environ["JWT_REFRESH_DAYS"]
DB_SERVER = environ["DB_SERVER"]
MAIL_USERNAME = environ["MAIL_USERNAME"]
MAIL_PASSWORD = environ["MAIL_PASSWORD"]
MAIL_SERVER = environ["MAIL_SERVER"]
REDIS_SERVER = environ["REDIS_SERVER"]
BASE_URL = environ["BASE_URL"]